### ISSUE TITLE
Raw results availability

### ISSUE THREAD

**Issue by penfever** [naszilla/tabzilla#92]
Hi, TabZilla team!  Thanks very much for putting together this repository.

On the Arxiv page associated with this repository (2305.02997), it says, our codebase and all raw results are available at [this https URL](https://github.com/naszilla/tabzilla). However, I cannot find the raw experimental results anywhere in this repository. Can you please update the README to indicate where the raw results are?

**Comment by duncanmcelfresh** [comment]
Hi Ben, thanks for noticing this - we are currently working on updating the README, and plan to push some changes in the next week or so.

The raw results are hosted on google drive, and we have a tutorial notebook on how to access and interpret these results here: https://github.com/naszilla/tabzilla/blob/main/TabZilla/tutorials/analyze_metadataset.ipynb

**Comment by duncanmcelfresh** [comment]
resolved some time ago
