### ISSUE TITLE
Is the average ranking meaningful since each algorithm is test on different number of datasets ?

### ISSUE THREAD

**Issue by abvesa** [naszilla/tabzilla#95]

**Comment by duncanmcelfresh** [comment]
it seems this is a question about our paper and not this repo. good question though - when we show aggregated rankings (min, max, mean, median, ...) we are aggregating over the **same group of datasets** for each algorithm. so: when we show average rankings for different algorithms, these averages are taken over the exact same datasets.

**Comment by abvesa** [comment]
hi, thanks for the reply, and sorry about not mentioning the question is for the paper.
I'm now trying to reproduce the table 5 result in the paper, with the results `metadataset_clean` and `metafeature_clean` downloaded from google drive and the provided scripts `1-aggregate-results` and `2-performance-rankings`.

Since table 5 focus on only 36 Tabular Benchmark Suite datasets, I then subset the `agg_df_with_default` and `agg_df` using the datasets mentioned in `/scripts/HARD_DATASETS_BENCHMARK.sh`, before calculating ranks and saving result. 

I add a column called `dataset_count` to see how many datasets were used for each algorithm calculating its statistics across all results, bellow is the result I got. We can see some of the numbers are different from the paper and some are not, more importantly, 
`catboost, `saint` and `node` have exact same `time/1000 inst.` compare to the paper, but the results of these three algorithms are calculated using different numbers of datasets.

I'm curious about if I am using the code wrong, can you provided some advice for how to fully reproduce the results of table 5, thank you !!

![螢幕擷取畫面 2023-12-23 103559](https://github.com/naszilla/tabzilla/assets/22200176/8d807f80-9313-4d39-83f4-9ef62f2b3026)
![螢幕擷取畫面 2023-12-23 103700](https://github.com/naszilla/tabzilla/assets/22200176/9b56f381-d375-4d51-af00-72c83e6f8831)
