### ISSUE TITLE
Unable to run 1-aggregate-results - Permission Issue

### ISSUE THREAD

**Issue by junweima** [naszilla/tabzilla#97]
May I ask how did you get `1-aggregate-results` running? 

A key file named `metadataset.csv` is missing for me. I then tried to generate file using `tabzilla/TabZilla/tabzilla_results_aggregator.py`. However, I then encountered permission issue from google cloud

> google.api_core.exceptions.Forbidden: 403 GET https://storage.googleapis.com/storage/v1/b/tabzilla-results/o?projection=noAcl&prefix=results&prettyPrint=false: \myemail@gmail.com does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist).

**Comment by duncanmcelfresh** [comment]
hi @junweima, the tutorial `1-aggregate-results.ipynb` should not require the metadataset file. However, the tutorial [`analyze_metadataset.ipynb`](https://github.com/naszilla/tabzilla/blob/main/TabZilla/tutorials/analyze_metadataset.ipynb) does require this file. The metadataset csv is in a public gcloud folder - the link is in this tutorial notebook.

I will close this issue for now, please comment and reopen if I misunderstood the problem.
